development:
  adapter: mysql2
  database: spree_development_2_2

test:
  adapter: postgresql
  database: spree_test_edge
  username: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: spree_development_2_2
